apiVersion: v1
kind: Service
metadata:
  name: wiki
spec:
  type: LoadBalancer   #NodePort
  selector:
    app: wiki
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
