apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
      - name: wiki
        image: ghcr.io/requarks/wiki:2  # Image de Wiki.js
        env:
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: db
        - name: DB_USER
          value: wikijs
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: wiki-db-secret
              key: DB_PASS
        - name: DB_NAME
          value: wiki
        - name: ADMIN_EMAIL
          value: coulwao@gmail.com
        - name: ADMIN_PASS
          value: SuperSecret123
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10

      - name: nginx
        image: thomcoul/custom-nginx:latest  # Image custom NGINX
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config

---

apiVersion: v1
kind: Service
metadata:
  name: wiki
spec:
  selector:
    app: wiki
  ports:
  - protocol: TCP
    port: 80   # NGINX écoute sur le port 80
    targetPort: 80
  type: NodePort  # Pour exposer le service vers l'extérieur
